export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  content: string[]
}

export const categoryColors: Record<string, string> = {
  Tips: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400',
  Engineering: 'bg-violet-500/10 text-violet-600 dark:text-violet-400',
  Guide: 'bg-amber-500/10 text-amber-600 dark:text-amber-400',
  Product: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400',
}

export const posts: BlogPost[] = [
  {
    slug: 'reduce-no-shows-automated-reminders',
    title: '5 Ways to Reduce No-Shows with Automated Reminders',
    excerpt: 'Learn how SMS and email reminders can cut your no-show rate by up to 70%.',
    category: 'Tips',
    date: 'Mar 10, 2026',
    readTime: '5 min read',
    content: [
      'No-shows are one of the biggest challenges for service-based businesses. On average, 20-30% of scheduled appointments result in no-shows, costing businesses thousands of dollars in lost revenue every year. The good news? Automated reminders can cut that rate by up to 70%.',
      '## 1. Send a Confirmation Immediately After Booking',
      'The moment a customer books an appointment, send an instant email and SMS confirmation. This sets expectations and gives them a reference they can check later. BookFlow does this automatically — the second a booking is created, the customer receives a professional confirmation email with all the details: service name, date, time, and a link to manage their booking.',
      '## 2. Send a Reminder 24 Hours Before',
      'A reminder the day before is the single most effective way to reduce no-shows. People are busy, and a gentle nudge goes a long way. BookFlow\'s scheduled reminder system checks for upcoming bookings every 15 minutes and sends SMS reminders automatically. The reminder includes the service, time, and a note about the cancellation policy.',
      '## 3. Send a Same-Day Reminder 2 Hours Before',
      'For same-day appointments, a reminder 2 hours before the slot gives customers enough time to prepare and show up. This is especially effective for services like consultations and design reviews where clients might lose track of time.',
      '## 4. Include Easy Rescheduling Options',
      'Don\'t just remind — make it easy to reschedule. If a customer realizes they can\'t make it, a one-click reschedule link is far better than a no-show. BookFlow\'s reminder messages include a direct link to the rescheduling page where customers can pick a new date and time instantly.',
      '## 5. Track and Adapt',
      'Use your analytics dashboard to identify patterns. Which services have the highest no-show rates? Which time slots? BookFlow\'s dashboard shows no-show rates by service, day of week, and time of day, so you can adjust your scheduling strategy accordingly.',
      '## The Bottom Line',
      'Automated reminders aren\'t just a convenience — they\'re a revenue protection strategy. With BookFlow\'s built-in email and SMS notification system, you can set it up once and let it work in the background, saving you time and money on every booking.',
    ],
  },
  {
    slug: 'double-booking-prevention-postgresql',
    title: 'How BookFlow Handles Double Bookings at the Database Level',
    excerpt: 'A technical deep dive into our PostgreSQL exclusion constraints and advisory locks.',
    category: 'Engineering',
    date: 'Mar 5, 2026',
    readTime: '8 min read',
    content: [
      'Double bookings are the worst kind of bug in a scheduling system. Two customers show up for the same slot, and now you have an angry client and a reputation problem. At BookFlow, we solve this with a two-layer defense system that makes double bookings mathematically impossible.',
      '## The Problem with Naive Approaches',
      'Most booking systems check availability with a simple SELECT query: "Are there any bookings for this service, date, and time?" If not, insert the new booking. The problem? Two concurrent requests can both pass the check before either one inserts. This is a classic race condition.',
      '## Layer 1: Advisory Locks',
      'Before checking availability, BookFlow acquires a PostgreSQL advisory lock scoped to the service ID and date. This serializes concurrent booking attempts for the same slot. If two requests arrive simultaneously, one waits until the other completes. The lock is released automatically at the end of the transaction.',
      '## Layer 2: EXCLUDE Constraint',
      'Even if the advisory lock somehow fails (network issues, connection pooling edge cases), PostgreSQL\'s EXCLUDE constraint is the hard backstop. We use the btree_gist extension to create an exclusion constraint on the bookings table that prevents any two active bookings from overlapping in time for the same service.',
      '```sql\nALTER TABLE bookings\n  ADD CONSTRAINT bookings_no_overlap\n    EXCLUDE USING gist (\n      service_id WITH =,\n      tsrange(\n        (booking_date + start_time)::timestamp,\n        (booking_date + end_time)::timestamp,\n        \'[)\'\n      ) WITH &&\n    )\n    WHERE (status NOT IN (\'cancelled\', \'no_show\'));\n```',
      '## How They Work Together',
      'The advisory lock is the fast path — it prevents most conflicts before they hit the database. The EXCLUDE constraint is the safety net — even if two requests slip past the lock, PostgreSQL will reject one with error code 23P01 (exclusion_violation). Our error handler catches this and returns a clean 409 SLOT_CONFLICT response to the client.',
      '## The Result',
      'In production, we have processed hundreds of thousands of bookings with zero double-booking incidents. The two-layer approach gives us both performance (advisory locks are fast) and correctness (EXCLUDE constraints are bulletproof). This is the kind of engineering that you don\'t see in the UI, but it\'s what makes the platform reliable.',
    ],
  },
  {
    slug: 'complete-guide-online-booking-small-business',
    title: 'The Complete Guide to Online Booking for Small Businesses',
    excerpt: 'Everything you need to know about setting up online scheduling from scratch.',
    category: 'Guide',
    date: 'Feb 28, 2026',
    readTime: '12 min read',
    content: [
      'If you\'re still taking bookings over the phone or through email, you\'re leaving money on the table. Online booking isn\'t just a convenience — it\'s a competitive advantage. Here\'s everything you need to know to get started.',
      '## Why Online Booking Matters',
      'Studies show that 67% of customers prefer booking online rather than calling. And 40% of online bookings happen outside business hours — that\'s revenue you\'re missing if you don\'t have a 24/7 booking system. An online booking platform works while you sleep.',
      '## Step 1: Define Your Services',
      'Start by listing every service you offer. For each one, define the name, duration, price, and a short description. Be specific — "60-minute Strategy Consultation" is better than just "Consultation". In BookFlow, you can create unlimited services with categories, making it easy for customers to find what they need.',
      '## Step 2: Set Your Availability',
      'Decide your working hours and days. Block off lunch breaks, holidays, and personal time. BookFlow generates available time slots automatically based on your service duration and working hours. If a 60-minute service starts at 9 AM, the next available slot is 10 AM.',
      '## Step 3: Set Up Notifications',
      'Configure email and SMS notifications for booking confirmations and reminders. BookFlow supports both out of the box — just add your email (we use Gmail SMTP) and optionally connect Twilio for SMS. Customers get instant confirmation and automated reminders before their appointment.',
      '## Step 4: Accept Payments',
      'Collecting payment at booking time reduces no-shows dramatically. Even a small deposit creates commitment. BookFlow\'s integrated payment system lets you collect full or partial payment during the booking process.',
      '## Step 5: Share Your Booking Link',
      'Once set up, share your booking page link on your website, social media, email signature, and Google Business profile. The easier it is to find, the more bookings you\'ll get.',
      '## Step 6: Monitor and Optimize',
      'Use your dashboard to track which services are most popular, which times fill up fastest, and where customers drop off. BookFlow\'s analytics show revenue trends, booking patterns, and customer behavior so you can make data-driven decisions.',
      '## Getting Started',
      'The best time to set up online booking was yesterday. The second best time is today. With BookFlow, you can go from zero to accepting bookings in under 10 minutes. Create your services, set your hours, and share your link — it\'s that simple.',
    ],
  },
  {
    slug: 'google-calendar-sync-feature',
    title: 'New Feature: Google Calendar Sync',
    excerpt: 'Your bookings now sync automatically to Google Calendar. Here\'s how to set it up.',
    category: 'Product',
    date: 'Feb 20, 2026',
    readTime: '3 min read',
    content: [
      'We\'re excited to announce Google Calendar integration in BookFlow. Now every confirmed booking can be added to your Google Calendar with one click.',
      '## How It Works',
      'After a booking is confirmed, you\'ll see an "Add to Google Calendar" button. Click it, and a pre-filled Google Calendar event opens with all the details: service name, date, time, duration, and a description with the booking ID.',
      '## What Gets Synced',
      'Each calendar event includes the service name as the event title, the exact date and time, the duration based on the service configuration, and a description that includes the booking ID and any notes from the customer.',
      '## For Customers',
      'Customers see the "Add to Google Calendar" button on the booking confirmation dialog and in their booking cards on the dashboard. One click and the appointment is in their calendar with a reminder.',
      '## Why This Matters',
      'Calendar sync reduces no-shows because the appointment is always visible. Customers get native Google Calendar reminders on top of BookFlow\'s SMS and email reminders. It\'s one more layer of communication that keeps everyone on the same page.',
      '## Coming Soon',
      'We\'re working on automatic two-way sync with OAuth so bookings are added to your calendar without any manual action. Stay tuned for updates.',
    ],
  },
  {
    slug: 'sqlite-to-postgresql-migration',
    title: 'Why We Migrated from SQLite to PostgreSQL',
    excerpt: 'The story of our database migration and why it was worth the effort.',
    category: 'Engineering',
    date: 'Feb 15, 2026',
    readTime: '6 min read',
    content: [
      'BookFlow started with SQLite. It was fast to set up, required zero configuration, and worked perfectly for development. But as the platform grew, we hit limitations that forced us to migrate to PostgreSQL.',
      '## Why SQLite Worked at First',
      'SQLite is an incredible database for prototyping. No server to manage, no connection strings to configure, just a single file. For a booking platform with a few hundred users, it handled everything we threw at it. Our initial schema, seed data, and queries all worked beautifully.',
      '## Where SQLite Fell Short',
      'The problems started when we needed concurrent writes. SQLite uses file-level locking — only one write can happen at a time. With multiple users booking simultaneously, we started seeing "database is locked" errors. We also couldn\'t use advanced features like advisory locks, EXCLUDE constraints, or JSONB columns.',
      '## The Migration Process',
      'We rewrote our database layer to use the pg (node-postgres) library with a connection pool. Every SQL query was reviewed for PostgreSQL compatibility — SQLite\'s type system is much more flexible, so we had to add explicit casts and type constraints. We created a comprehensive schema.sql with proper UUID primary keys, TIMESTAMPTZ columns, CHECK constraints, and indexes.',
      '## The Biggest Wins',
      'After migrating, we gained EXCLUDE constraints for double-booking prevention (impossible in SQLite), advisory locks for serializing concurrent bookings, JSONB columns for flexible metadata storage, proper timestamp handling with timezone support, and partial indexes for query performance.',
      '## What We Learned',
      'Start with the database you\'ll use in production. SQLite is great for prototyping, but migrating later costs more than setting up PostgreSQL on day one. The pg library with a connection pool is straightforward to configure, and tools like pgAdmin make it easy to inspect your data.',
      '## The Result',
      'BookFlow now handles concurrent bookings without any locking issues. Our double-booking prevention is enforced at the database level. Query performance improved significantly with proper indexes. And we have a solid foundation for future features like full-text search and real-time subscriptions.',
    ],
  },
  {
    slug: 'modern-saas-ui-nextjs-tailwind',
    title: 'Building a Modern SaaS UI with Next.js and Tailwind',
    excerpt: 'Design decisions and patterns behind the BookFlow frontend.',
    category: 'Engineering',
    date: 'Feb 8, 2026',
    readTime: '10 min read',
    content: [
      'BookFlow\'s frontend is built with Next.js 16, Tailwind CSS 4, and a collection of carefully chosen libraries. Here\'s a look at the design decisions that shape the user experience.',
      '## The Tech Stack',
      'Next.js 16 with the App Router gives us file-based routing, server components, and streaming. Tailwind CSS 4 provides utility-first styling with zero runtime cost. Radix UI primitives handle accessible dialogs, dropdowns, and form elements. Framer Motion adds smooth animations. Zustand manages client state. React Hook Form with Zod handles form validation.',
      '## Design System',
      'We built a consistent design system with a limited color palette (stone neutrals with green accents), consistent spacing (multiples of 4px), rounded corners (xl for cards, full for badges), and a clear typography hierarchy. Every component uses CSS variables for colors so dark mode works automatically.',
      '## Aurora Backgrounds',
      'The animated gradient backgrounds on our marketing pages use pure CSS keyframes. Four blurred blobs with different colors and animation timings create an aurora effect. The animations only use transform and opacity — both GPU-composited properties — so performance stays smooth even on mobile.',
      '## Glassmorphism Filter Bars',
      'The search and filter bars use backdrop-blur-xl with semi-transparent backgrounds. In light mode: bg-white/60. In dark mode: bg-white/5. This creates a frosted glass effect that looks premium without sacrificing readability.',
      '## 3D Tilt Cards',
      'Service cards use react-parallax-tilt for subtle 3D rotation on hover. Combined with a custom card-glow CSS class that adds a purple shadow bloom, the cards feel interactive and premium. The tilt angle is limited to 8 degrees to keep it subtle.',
      '## Staggered Animations',
      'Lists and grids use staggered entrance animations — each item delays 60-80ms after the previous one. This creates a cascade effect that makes the page feel alive without being distracting. We use Framer Motion\'s transition delay prop with the item index.',
      '## Dark Mode',
      'Dark mode is class-based (the html element gets a "dark" class). Tailwind\'s dark: variant handles most styling. For custom CSS like aurora blobs, we use :where(.dark) selectors to increase opacity and vibrancy on dark backgrounds.',
      '## Performance',
      'All animations use will-change: transform, opacity for GPU acceleration. Images are lazy-loaded. The bundle is kept small by using tree-shakeable libraries. Tailwind purges unused styles in production. The result: a fast, smooth experience even on lower-end devices.',
    ],
  },
]

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find(p => p.slug === slug)
}
